### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by nipunarora** [vikasnkumar/hotpatch#11]
I looked at the help instructions

Usage: ./bin/hotpatcher [options] <PID of process to patch>

Options:
-h           This help message
-V           Version number.
-v[vvvv]     Enable verbose logging. Add more 'v's for more
-N           Dry run. Do not modify anything in process
-l <.so>     Path or name of the .so file to load. Switches off execution pointer reset
-s <name>    Symbol to invoke during the dll inject. Optional.
-x <name>    Set execution pointer to symbol. Cannot be set with -s option

I still do not understand how to use this however... let's say I have a process with a PID x, and I want to instrument function foo, with an instrumentation in a function bar.

Could you explain the steps I need to take?

**Comment by vikasnkumar** [comment]
Read the README file. it is explained.
