### ISSUE TITLE
Segmentation fault after injecting library

### ISSUE THREAD

**Issue by qwrt747** [vikasnkumar/hotpatch#12]
hi, im trying  comand line version of hotpatcher by your test library and symbol, it was done and date has written in log file, but right after injection,the target application get crashed and segfault error shown.

is it regular or something is wrong
im using ubuntu 14.04 i386

edit:
it has arbitrary functionality! sometimes is done correctly ,but now, it just inject in my self-written app and for other processes like firefox (in -vvv mode) prints:
```
...
[hotpatch_inject_library:783] mysym not invoked as dlsym() wasn't found.
...
```
how to solve it?
thanks

**Comment by qwrt747** [comment]
finally it seems , a delay solves every thing.
injecting after completely starting the target solved my problems.
good luck

**Comment by vikasnkumar** [comment]
Glad that you solved your race condition.  sorry was unable to respond earlier.
