### ISSUE TITLE
Trouble attaching to container processes.

### ISSUE THREAD

**Issue by DevasiaThomas** [vikasnkumar/hotpatch#16]
Hi Vikas,

I'm trying to attach to a container process. This is what I get

```
[ld_load_maps:278] Max number of mappings present: 19
[ld_find_library:447] Library /lib64/ld-linux-x86-64.so.2 not found in procmaps
[hotpatch_gather_functions:93] /lib64/ld-linux-x86-64.so.2 not mapped.
[ld_find_library:376] Doing best substring search for ld.
[ld_find_library:440] Found entry /lib/x86_64-linux-gnu/ld-2.19.so matching ld
[ld_find_library:376] Doing best substring search for libc.
[ld_find_library:440] Found entry /lib/x86_64-linux-gnu/libc-2.19.so matching libc
[ld_find_library:376] Doing best substring search for libdl.
[ld_find_library:447] Library libdl not found in procmaps
[hotpatch_gather_functions:102] libdl not mapped.
[ld_find_library:376] Doing best substring search for libpthread.
[ld_find_library:447] Library libpthread not found in procmaps
[hotpatch_gather_functions:104] libpthread not mapped.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
[hotpatch_gather_functions:106] malloc not found in libc.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
[hotpatch_gather_functions:107] realloc not found in libc.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
[hotpatch_gather_functions:108] free not found in libc.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
[hotpatch_gather_functions:111] malloc not found in ld.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
[hotpatch_gather_functions:112] realloc not found in ld.
[exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open error. Error: No such file or directory
[ld_find_address:515] No symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
[hotpatch_gather_functions:113] free not found in ld.
[hotpatch_gather_functions:118] Some memory allocation routines are unavailable. Cannot proceed.
[hotpatch_create:224] Unable to find all the functions needed. Cannot proceed.
[hotpatch_inject_library:594] No malloc/dlopen found.
lib injection failed wit rc -1
```
I checked, those files exist within the containers filesystem, but it can't be opened. any clues why? This is a docker container.

**Comment by vikasnkumar** [comment]
Containers are not supported. Sorry. 

--
  Vikas Kumar
  vikas@vikaskumar.org



On Wed, Jun 27, 2018, at 6:32 PM, Devasia Thomas wrote:
> Hi Vikas,


> I'm trying to attach to a container process. This is what I get


> [ld_load_maps:278] Max number of mappings present: 19
> [ld_find_library:447] Library /lib64/ld-linux-x86-64.so.2 not found in
> procmaps [hotpatch_gather_functions:93] /lib64/ld-linux-x86-64.so.2
> not mapped. [ld_find_library:376] Doing best substring search for ld.
> [ld_find_library:440] Found entry /lib/x86_64-linux-gnu/ld-2.19.so
> matching ld [ld_find_library:376] Doing best substring search for
> libc. [ld_find_library:440] Found entry /lib/x86_64-linux-gnu/libc-
> 2.19.so matching libc [ld_find_library:376] Doing best substring
> search for libdl. [ld_find_library:447] Library libdl not found in
> procmaps [hotpatch_gather_functions:102] libdl not mapped.
> [ld_find_library:376] Doing best substring search for libpthread.
> [ld_find_library:447] Library libpthread not found in procmaps
> [hotpatch_gather_functions:104] libpthread not mapped.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
> [hotpatch_gather_functions:106] malloc not found in libc.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
> [hotpatch_gather_functions:107] realloc not found in libc.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/libc-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/libc-2.19.so
> [hotpatch_gather_functions:108] free not found in libc.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
> [hotpatch_gather_functions:111] malloc not found in ld.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
> [hotpatch_gather_functions:112] realloc not found in ld.
> [exe_open_filename:99] File(/lib/x86_64-linux-gnu/ld-2.19.so) open
> error. Error: No such file or directory [ld_find_address:515] No
> symbols found in /lib/x86_64-linux-gnu/ld-2.19.so
> [hotpatch_gather_functions:113] free not found in ld.
> [hotpatch_gather_functions:118] Some memory allocation routines are
> unavailable. Cannot proceed. [hotpatch_create:224] Unable to find all
> the functions needed. Cannot proceed. [hotpatch_inject_library:594] No
> malloc/dlopen found. lib injection failed wit rc -1
>> I checked, those files exist within the containers filesystem, but it
> can't be opened. any clues why? This is a docker container.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/vikasnkumar/hotpatch/issues/16

**Comment by DevasiaThomas** [comment]
Well, sure. Do you know or can you guess why, even though it finds libc it cannot open it?

**Comment by vikasnkumar** [comment]
It is unable to open the files like libc to read symbols. It’s the 7th
or 8th line in the log.
You should try testing with the sample application I provide. If
that doesn’t work it won’t work. Containers are just chroot jails
and the files need to be present in those locations which may need
to be created.
--
  Vikas Kumar
  vikas@vikaskumar.org



On Wed, Jun 27, 2018, at 7:03 PM, Devasia Thomas wrote:
> Well, sure. Do you know or can you guess why, even though it finds
> libc it cannot open it?> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/vikasnkumar/hotpatch/issues/16#issuecomment-400856596

**Comment by DevasiaThomas** [comment]
I will try what you asked. But I did verify that those files existed in the locations they were supposed to be within the containers FS. I can't figure out why hotpatch cannot open them.

**Comment by vikasnkumar** [comment]
I have never used containers for my software so I cannot tell you
what to do.
If you read the log you see the function exe_load_filename or similar.
There is an internal reentrant API that can open files. Try manually
writing a simple program that uses this API and running it in the
container. If that works then there must be a kernel setting that
disables loading from other processes. If it doesn’t work you can debug
with gdb because it is just an open() system call.
Try running as root to see if it is a permissions issue, which
doesn’t seem likely but with containers hard to tell what is allowed
and what isn’t.
By the way which container are you using and which OS version ? 



--
  Vikas Kumar
  vikas@vikaskumar.org



On Wed, Jun 27, 2018, at 8:44 PM, Devasia Thomas wrote:
> I will try what you asked. But I did verify that those files existed
> in the locations they were supposed to be within the containers FS. I
> can't figure out why hotpatch cannot open them.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/vikasnkumar/hotpatch/issues/16#issuecomment-400875056

**Comment by DevasiaThomas** [comment]
Okay I'll try that as well. Im using docker 1.12.6 on Redhat 7.4.1708 (core)

**Comment by vikasnkumar** [comment]
Closing since no issues reported.
