### ISSUE TITLE
Fail to load ELF for exe

### ISSUE THREAD

**Issue by zhuguoliang** [vikasnkumar/hotpatch#8]
I am running benchmark program GemsFDTD_base.gcc in spec06

I tried the following command : hotpatcher -l ./Release/libhotpatchtest.so -s mysym -vvv 15912
(15912 is the pid of GemsFDTD_base.gcc )

I got the following result:
Options Given:
Verbose Level: 2
Process PID: 15912
Symbol name: mysym
Library name: ./Release/libhotpatchtest.so
Dry run: false
[exe_load_headers:490] Entry point 0x3408048db0
[exe_load_headers:510] Error in loading section headers
[exe_load_symbols:539] Unable to load Elf details for /proc/15912/exe
[hotpatch_create:197] Unable to find any symbols in exe.
[hotpatch_inject_library:594] No malloc/dlopen found.

**Comment by vikasnkumar** [comment]
Sorry, just saw this. What operating system are you running here ?
